/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details on writing Custom Plugins, please refer to https://docs.gradle.org/8.4/userguide/custom_plugins.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the Java Gradle plugin development plugin to add support for developing Gradle plugins
    `java-gradle-plugin`
    `maven-publish`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
    withSourcesJar()
    withJavadocJar()
}

dependencies {
    implementation("dev.masecla:Modrinth4J:2.0.0")
    implementation("org.kohsuke:github-api:1.321")
    implementation("org.apache.httpcomponents.client5:httpclient5:5.3.1")
}

gradlePlugin {
    plugins {
        create("xyz.kyngs.mcupload.plugin") {
            id = "xyz.kyngs.mcupload.plugin"
            implementationClass = "xyz.kyngs.mcupload.plugin.MCUploadGradlePlugin"
            version = project.version
        }
    }
}

publishing {
    repositories {
        maven {
            name = "kyngsRepo"
            url = uri(
                    "https://repo.kyngs.xyz/gradle-plugins/"
            )
            credentials(PasswordCredentials::class)
            authentication {
                create<BasicAuthentication>("basic")
            }
        }
    }
}

version = "0.2.4"
group = "xyz.kyngs.mcupload"
