/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xyz.kyngs.mcupload.plugin;

import org.gradle.api.Project;
import org.gradle.api.Plugin;
import xyz.kyngs.mcupload.plugin.extension.MCUploadExtension;

public class MCUploadGradlePlugin implements Plugin<Project> {
    public void apply(Project project) {
        project.getExtensions().create("mcupload", MCUploadExtension.class, project);

        project.getTasks().register("release", MCReleaseTask.class)
                .configure(task -> {
                    task.setGroup("mcupload");
                });

        project.getTasks().register("syncReadme", MCReadmeSyncTask.class)
                .configure(task -> {
                    task.setGroup("mcupload");
                });
    }
}
