steps:
  build:
    image: "eclipse-temurin:17-alpine"
    commands:
      - "./gradlew licenseCheck build javadocJar"

  publish:
    image: "eclipse-temurin:17-alpine"
    commands:
      - "./gradlew publish -PkyngsRepoUsername=$${KYNGS_REPO_TOKEN} -PkyngsRepoPassword=$${KYNGS_REPO_SECRET}"
    when:
      - event: push
        branch:
          - master
    secrets: [ kyngs_repo_token, kyngs_repo_secret ]